# Generated by Django 4.0 on 2021-12-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pajak',
            old_name='pajak',
            new_name='rate',
        ),
    ]
